version: "3.1"
nlu:
- intent: chitchat/ask_name
  examples: |
    - What is your name?
    - Do you have a name for yourself?
    - What do people call you?
- intent: chitchat/ask_weather
  examples: |
    - What's the weather like today?
    - I like sunny days in Berlin.
    - Does it look sunny outside today?
- intent: faq/taste_description
  examples: |
    - Could you give me some insight into the taste of blue cheese?
    - Can you explain the flavor profile of blue cheese?
    - I've never tried blue cheese before, what should I expect it to taste like?
    - What does blue cheese taste like?
- intent: faq/spice_level
  examples: |
    - How spicy is traditional Thai curry?
    - Can you tell me about the spice level in Szechuan cuisine?
    - What should I expect in terms of heat when eating Mexican salsa?
    - Is Indian food generally very spicy?
- intent: out_of_scope
  examples: |
    - Who's the US President?
    - what is chatgpt ?
    - I want to order food
    - who is the creator of minecraft ?
- intent: request_restaurant
  examples: |
    - can i get [swedish](cuisine) food in any area
    - id like a restaurant
    - im looking for a restaurant
    - im looking for a restaurant that serves [mediterranean](cuisine) food
    - can i find a restaurant that serves [chinese](cuisine)
- intent: affirm
  examples: |
    - y
    - of course
    - that sounds good
    - yes
    - indeed
- intent: inform
  examples: |
    - what about [indian](cuisine) food
    - im looking for [tuscan](cuisine) food
    - id like [moroccan](cuisine) food
    - uh how about [turkish](cuisine) type of food
    - um [english](cuisine)
- intent: deny
  examples: |
    - I don't think so
    - never
    - no way
    - n
    - not really
    - don't like that
